# Generated by Django 2.0.2 on 2018-08-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180730_1030'),
        ('task', '0006_auto_20180801_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='tags',
            field=models.ManyToManyField(blank=True, to='project.Tag'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='project.Tag'),
        ),
    ]
