# Generated by Django 2.0.2 on 2018-03-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_delete_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='data',
        ),
    ]
