# Generated by Django 2.0.2 on 2018-09-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='format',
            field=models.CharField(blank=True, choices=[('xlsx', 'xlsx'), ('docx', 'docx'), ('csv', 'csv'), ('pdf', 'pdf'), ('json', 'json')], max_length=100),
        ),
    ]
