version: '3.2'

services:
    db:
        image: postgres:9.6
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    server:
        image: devtc/chrono:server-latest
        build:
          context: ./server/
          cache_from:
            - devtc/chrono:server-latest
        env_file:
            - .env
        command: ['/code/deploy/scripts/wait-for-it.sh', 'db:5432', '--', '/code/deploy/scripts/run_develop.sh']
        volumes:
            - ./server/:/code
            - ./media:/media
        ports:
            - '8010:8010'
        depends_on:
            - db

    client:
        image: devtc/chrono:client-latest
        build:
          context: ./client/
          cache_from:
            - devtc/chrono:client-latest
        env_file:
            - .env
        command: ['/code/scripts/run_develop.sh']
        volumes:
            - ./client/:/code
            - ./media:/media
        ports:
            - '3001:3001'
        depends_on:
            - server
