version: '3.2'

services:
    db:
        image: postgres:9.6
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    server:
        image: devtc/chrono:latest
        build:
          context: .
          cache_from:
            - devtc/chrono:latest
        env_file:
            - .env
        command: ['/code/scripts/wait-for-it.sh', 'db:5432', '--', '/code/scripts/run_develop.sh', 'server']
        volumes:
            - .:/code
            - ./media:/media
        ports:
            - '8010:8010'
        depends_on:
            - db

    client:
        image: devtc/chrono:latest
        build:
          context: .
          cache_from:
            - devtc/chrono:latest
        build: .
        env_file:
            - .env
        command: ['/code/scripts/run_develop.sh', 'client']
        volumes:
            - .:/code
            - ./media:/media
        ports:
            - '3001:3001'
        depends_on:
            - server
