version: '3.2'

services:
    db:
        image: postgres:9.6
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    server:
        image: devtc/chrono:server-prod-0.1
        build:
          context: ./server/
          cache_from:
            - devtc/chrono:server-latest
        env_file:
            - .env
        volumes:
            - ./media:/media
        ports:
            - '80:80'
        depends_on:
            - db
