version: '3.2'

services:
    db:
        image: postgres:9.6
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    server:
        image: devtc/chrono:prod-0.1
        build:
          context: .
          cache_from:
            - devtc/chrono:latest
        env_file:
            - .env
        command: ['/code/scripts/wait-for-it.sh', 'db:5432', '--', '/code/scripts/run_develop.sh', 'server']
        volumes:
            - ./media:/media
        ports:
            - '80:8010'
        depends_on:
            - db
