# Generated by Django 2.0.2 on 2018-03-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20180322_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='description',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='data',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='data',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='title',
        ),
    ]
