# Generated by Django 2.0.2 on 2018-07-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180730_1030'),
        ('task', '0003_auto_20180322_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='project.Tag'),
        ),
    ]
