# Generated by Django 2.0.2 on 2019-05-03 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0009_auto_20180910_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('public_holiday', 'Public Holiday'), ('office_holiday', 'Office Holiday'), ('sick_leave', 'Sick Leave'), ('office_event', 'Office Event'), ('miscellaneous', 'Miscellaneous')], max_length=64)),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remark_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remark_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified_at', '-created_at'],
                'abstract': False,
            },
        ),
    ]
