# Generated by Django 2.0.2 on 2018-10-30 11:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0010_dateremark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dateremark',
            unique_together={('user', 'date')},
        ),
    ]
